docker-compose.yml
docker/docker-compose.dev.yml
src/Endatix.Extensions.Hosting/AppBuilderExtensions.cs
src/Endatix.WebHost/appsettings.Development.json

Logs become large very fast becaus of logging /healthz requests every 5 s. To prevent this and to make the operation of Endatix API smoother, two things are done:
- Extend the healthcheck interval to15 sec (including a few more healthcheck config values changed that are better now)
- Changes in the Serilog setup to skip /healthz requests from logging and also change the logging level of Microsoft/System logging on dev so it doesn't automatically log all the requests (this is already done by Serilog)
closes #100

fix: Change DB and API healthcheck config, remove healthz requests from logs

---

src/Endatix.Core/Entities/Submission.cs
tests/Endatix.Core.Tests/Entities/SubmissionConstructorTests.cs
tests/Endatix.Core.Tests/Entities/SubmissionUpdateTests.cs
tests/Endatix.Core.Tests/ErrorMessages.cs
tests/Endatix.Core.Tests/SampleData.cs

CompletedAt  has not set on Submission creation. The is fixed, the logic is extracted to follow DRY and tests are added for Submission entity.
closes #101

fix: Set Submission CompletedAt time correctly

---

src/Endatix.Api/Endpoints/Forms/GetById.GetFormDefinitionByIdRequest.cs
src/Endatix.Api/Endpoints/Forms/GetById.GetFormDefinitionByIdValidator.cs
src/Endatix.Api/Endpoints/Forms/GetById.cs
src/Endatix.Api/Endpoints/Forms/PartialUpdate.PartialUpdateFormRequest.cs
src/Endatix.Api/Endpoints/Forms/PartialUpdate.PartialUpdateFormResponse.cs
src/Endatix.Api/Endpoints/Forms/PartialUpdate.PartialUpdateFormValidator.cs
src/Endatix.Api/Endpoints/Forms/PartialUpdate.cs
src/Endatix.Api/Endpoints/Forms/Update.UpdateFormRequest.cs
src/Endatix.Api/Endpoints/Forms/Update.UpdateFormResponse.cs
src/Endatix.Api/Endpoints/Forms/Update.UpdateFormValidator.cs
src/Endatix.Api/Endpoints/Forms/Update.cs
src/Endatix.Core/UseCases/Forms/GetById/GetFormDefinitionByIdHandler.cs
src/Endatix.Core/UseCases/Forms/GetById/GetFormDefinitionByIdQuery.cs
src/Endatix.Core/UseCases/Forms/PartialUpdate/PartialUpdateFormCommand.cs
src/Endatix.Core/UseCases/Forms/PartialUpdate/PartialUpdateFormHandler.cs
src/Endatix.Core/UseCases/Forms/Update/UpdateFormCommand.cs
src/Endatix.Core/UseCases/Forms/Update/UpdateFormHandler.cs
tests/Endatix.Core.Tests/SampleData.cs
tests/Endatix.Core.Tests/UseCases/Forms/GetById/GetFormByIdHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/GetById/GetFormByIdQueryTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/PartialUpdate/PartialUpdateFormCommandTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/PartialUpdate/PartialUpdateFormHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/Update/UpdateFormCommandTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/Update/UpdateFormHandlerTests.cs

A form needs to have the ability to be edited and displayed. This is achieved by three endpoints:
- `GET forms/{formId}`
- `PUT forms/{formId}`
- `PATCH forms/{formId}`
The three endpoints are added to Endatix API and they strictly follow the way the corresponding endpoints for form definitions are implemented.
**Note:** #99 doesn't include creating GET endpoint but missing such will be a missing functionality in an API that provides endpoints for creating, updating and listing forms so it is also added in this PR.
closes #99

feat: Add GET PUT and PATCH endpoints for a form

---

src/Endatix.Core/Infrastructure/Messaging/MediatRDomainEventDispatcher.cs
src/Endatix.Core/Infrastructure/Messaging/TaskToThreadPoolPublisher.cs
src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
tests/Endatix.Core.Tests/Endatix.Core.Tests.csproj
tests/Endatix.Core.Tests/Infrastructure/Messaging/TaskToThreadPoolPublisherTests.cs

* Adding fire and forget publishing of MediatR notifications using custom `INotificationPublisher` -> `TaskToThreadPoolPublisher`. Next level of improvement will be using a queue for decoupled processing of long running background tasks
* Previously NotificatonPublisher was await foreach before returning the control flow making it impractical for our use case of IO tasks like sending emails.
* Now all tasks are sent to the tread pool and control flow is returned back immediately
* Now exceptions in the notifications handlers don't cause exceptions in the main control flow
* Adding tests to validate the desired behavior
Resolves #129 
These are logs to show how does this behave. Note the thread was released in 4ms to finalize the response and …

feat: Adding fire and forget publishing of MediatR notifications using custom INotificationPublisher

---

src/Endatix.Api/Endpoints/Assistant/DefineForm.DefineFormRequest.cs
src/Endatix.Api/Endpoints/Assistant/DefineForm.DefineFormResponse.cs
src/Endatix.Api/Endpoints/Assistant/DefineForm.DefineFormValidator.cs
src/Endatix.Api/Endpoints/Assistant/DefineForm.cs
src/Endatix.Core/Abstractions/IAssistantService.cs
src/Endatix.Core/UseCases/Assistant/DefineForm/AssistedDefinitionDto.cs
src/Endatix.Core/UseCases/Assistant/DefineForm/DefineFormCommand.cs
src/Endatix.Core/UseCases/Assistant/DefineForm/DefineFormHandler.cs
src/Endatix.Infrastructure/Assistant/AssistantOptions.cs
src/Endatix.Infrastructure/Assistant/AssistantService.cs
src/Endatix.Infrastructure/Endatix.Infrastructure.csproj
src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
src/Endatix.WebHost/appsettings.Development.json
src/Endatix.WebHost/appsettings.json

Added endpoint POST assistant/forms/define according to the description of #140
closes #140
Example testing of the three scenarios from the issue:
1. Send request with prompt="I need a survey for movie feedback", check the returned definition and keep the assistant and thread IDs. This can be the case when a new form is created from scratch with AI.
2. Send request with prompt="Add a gender question" and the assistant and thread IDs from point 1, check the returned updated definition and keep it. This can be the case to continue an ongoing chat for editing a form with AI, no matter if it's a new or existing form.
3. Send request with prompt="Add three standard questions about Terminator 2" and the returned definition from point 2, check the returned updated definition. This can be the …

feat: POC AI form creation

---

src/Endatix.Api/Endpoints/Assistant/DefineForm.DefineFormResponse.cs
src/Endatix.Api/Endpoints/Assistant/DefineForm.cs
src/Endatix.Core/UseCases/Assistant/DefineForm/AssistedDefinitionDto.cs
src/Endatix.Infrastructure/Assistant/AssistantService.cs

Added a new field in the response called `AssistantResponse` that returns a human readable response from the AI Assistant. The response's `Definition` field is now optional as not every prompt makes changes to the definition.

feat: [POC] Return AssistantResponse in DefineForm endpoint

---

src/Endatix.Core/Abstractions/IPluginInitializer.cs
src/Endatix.Core/Features/WebHooks/ActionName.cs
src/Endatix.Core/Features/WebHooks/ActionNameExtensions.cs
src/Endatix.Core/Features/WebHooks/ActionNames.cs
src/Endatix.Core/Features/WebHooks/IWebHookService.cs
src/Endatix.Core/Features/WebHooks/WebHookMessage.cs
src/Endatix.Core/Features/WebHooks/WebHookOperation.cs
src/Endatix.Core/Features/WebHooks/WebHookRequestHeaders.cs
src/Endatix.Core/Handlers/SubmissionCompletedHandler.cs
src/Endatix.Core/UseCases/Submissions/SubmissionDto.cs
src/Endatix.Infrastructure/Endatix.Infrastructure.csproj
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTaskWebHookService.cs
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTasksQueue.cs
src/Endatix.Infrastructure/Features/WebHooks/IBackgroundTasksQueue.cs
src/Endatix.Infrastructure/Features/WebHooks/TaskInstructions.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookBackgroundWorker.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookServer.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookSettings.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHooksPlugin.cs
src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
src/Endatix.Infrastructure/Setup/ServiceCollectionExtensions.cs
src/Endatix.WebHost/appsettings.Development.json
tests/Endatix.Core.Tests/Features/WebHooks/ActionNamesTests.cs
tests/Endatix.Core.Tests/Features/WebHooks/WebHookMessageTests.cs
tests/Endatix.Core.Tests/Features/WebHooks/WebHookOperationTests.cs

- Added firing web hooks on Form Submission event handler
- Added support for multiple Urls destination
- All web hooks are fired in background threads not blocking the UI of the operation
- Added resilience strategy via HTTP Resiliance libraries - https://learn.microsoft.com/en-us/dotnet/core/resilience/http-resilience?tabs=dotnet-cli. 
- Added strategy to send headers with information on EventName, Entity & Action
- Added configs to modify RetryAttempts, Timeouts, Concurrency and other options
- Added tests for the Endatix.Core part of the feature (Endatix.
>[!IMPORTANT]
> - Documentation  is out of scope as it's blocked by merging auth PR. Task has been created - https://github.com/endatix/endatix/issues/170
> - Unit Tests in for the WebHooks parts of the code located in …

feat: Form Submission Webhook

---

src/Endatix.Api/Setup/MiddlewareExtensions.cs

Address the annoying issue with hitting 404 everytime we go to https://localhost:5001. No more... 😎 
- Now when you go to https://localhost:5001/, you will be redirected to https://localhost:5001/swagger/index.html
- Also Swagger won't generate on Prod as it's typically recommended
- We can generate the API swagger json at build time at later stage
No issue

feat: Adding default redirect from root to swagger for Non Prod environments

---

tests/Endatix.Api.Tests/Endpoints/Submissions/GetByTokenTests.cs
tests/Endatix.Api.Tests/Endpoints/Submissions/PartialUpdateByTokenTests.cs
tests/Endatix.Core.Tests/SampleData.cs
tests/Endatix.Core.Tests/UseCases/Submissions/GetByToken/GetByTokenHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenHandlerTests.cs
tests/Endatix.Infrastructure.Tests/Features/Submissions/SubmissionTokenServiceResolveTokenTests.cs

Not sure why the build didn't fail locally, but it fail after we have merged into `main`. Fixed several tests and started idea to have more data into the `SampleData`.
Should take us less code to generate mock objects. Maybe a mock factory might help to further develop this concept.

fix: Fixing build issues detected post merge

---

src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.PartialUpdateSubmissionByTokenValidator.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenCommand.cs
tests/Endatix.Core.Tests/ErrorMessages.cs
tests/Endatix.Core.Tests/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenCommandTests.cs

- As part of the #237 task, have encountered a bug in the Partial submission server side validation of the CurrentPage prop. This is a fix to allow for currentPage starting from 0 as default for multi page and single page forms
- Adding couple of tests to cover related fail scenarios
List any related issues (e.g., fixes #123, addresses #456).

fix: Adding fix for current page set to zero as starting index

---

.github/workflows/build-ci.yml
apps/endatix-hub/README.md
apps/endatix-hub/package.json
apps/endatix-hub/pnpm-lock.yaml
apps/endatix-hub/vitest.config.mts

We needed this to prevent builds which have failing tests or linting issues.
Now there will be two builds running in parallel for the Endatix API and the Endatix Hub:
Also, we will calculate test coverage for the Endatix Hub and will NOT upload to Coveralls as we won't do this fo rnow
>[!IMPORTANT]
>There's way to conditionally trigger the jobs only if files in certain folders have changed, but we won't do this now as well
closes #277

ci: Adding Endatix Hub to CI Process

---

.vscode/launch.json
src/Endatix.Core/Integrations/Slack/ISlackClient.cs
src/Endatix.Core/UseCases/Submissions/Create/CreateSubmissionHandler.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdate/PartialUpdateSubmissionHandler.cs
src/Endatix.Core/UseCases/Submissions/Update/UpdateSubmissionHandler.cs
src/Endatix.Infrastructure/AssembyReference.cs
src/Endatix.Infrastructure/Integrations/Slack/SlackClient.cs
src/Endatix.Infrastructure/Integrations/Slack/SlackSettings.cs
src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
src/Endatix.Infrastructure/Setup/ServiceCollectionExtensions.cs
src/Endatix.WebHost/appsettings.Development.json
src/Endatix.WebHost/appsettings.json
tests/Endatix.Core.Tests/UseCases/Submissions/Create/CreateSubmissionHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/PartialUpdate/PartialUpdateSubmissionHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/Update/UpdateSubmissionHandlerTests.cs

Created a basic client for the Slack API. Added a handler for the submission complete event. Created settings infrastructure for the Slack integration - configuration is doen through the appsettings.json file.
To test this you will need a Slack bearer token and access to a test Slack channel within the Endatix space.
The Slack message does not refer to the form by Name, due to an issue with DI of the Forms repository. A new issue will be created for it.
TODOs:
- Fix Form repo issue
- Add throttling (Slack limit is 1 message per second per channel)
- Add retry mechanism
Related to issue #289 

feat: feature slack notification message integration

---

apps/endatix-hub/app/(main)/forms/[formId]/ui/form-editor.tsx

Includes the described in #286 changes and additionally on an attempt to close the browser with unsaved changes there is a confirmation dialog.
**Note**
The user still can leave the screen with unsaved changes if they click to some other screen on the side menu bar. Confirmation dialog for this case is not a part of the task. However, I tried to add such logic but it seems changes need to be made on higher level in the whole application to make this possible so I left it as a future enhancement.
closes #286

feat: Design Form saving behavior changes

---

apps/endatix-hub/app/(main)/forms/[formId]/ui/form-editor.tsx
apps/endatix-hub/app/(main)/forms/[formId]/update-form-definition-json.action.ts
apps/endatix-hub/services/api.ts
src/Endatix.Core/Specifications/FormsWithSubmissionsCountSpec.cs
src/Endatix.Core/UseCases/Forms/Create/CreateFormHandler.cs

A new form is created with draft form definition. When it is updated in the Form Designer, the draft is set to false. The Forms screen does not display draft forms. If a form with name "New Form" is opened in the Designer, the form name is set in editing mode.
closes #318

feat: Create new forms as draft and do not display drafts on the forms screen

---

src/Endatix.Infrastructure/Integrations/Slack/SlackClient.cs
src/Endatix.Infrastructure/Integrations/Slack/SlackSettings.cs
src/Endatix.WebHost/appsettings.Development.json
src/Endatix.WebHost/appsettings.json

Only check for the other Slack settings if `Active==true` and only send notifications if `Active==true`
closes https://github.com/endatix/endatix-private/issues/27

fix: Do not send Slack notifications when they are not active

---

src/Endatix.Api/Common/FilteredRequestValidator.cs
src/Endatix.Core/Specifications/Parameters/FilterCriterion.cs
tests/Endatix.Api.Tests/Common/FilteredRequestValidatorTests.cs
tests/Endatix.Core.Tests/ErrorMessages.cs
tests/Endatix.Core.Tests/Specifications/Parameters/FilterCriterionTests.cs

Filters with time like e.g. `created>2025-01-05T15:14:13` led to bad requests because of the way they are parsed - the `:` in the time was confused with the `:` used as equal operator. This is fixed by changing the parsing logic - now it's clearer and more robust.
closes #346

fix: Filtering by time results Bad Request

---

apps/endatix-hub/.env.example
apps/endatix-hub/app/(main)/dashboard/page.tsx
apps/endatix-hub/app/(main)/page.tsx
apps/endatix-hub/env.d.ts
apps/endatix-hub/features/storage/__tests__/infrastructure/storage-service.test.ts
apps/endatix-hub/features/storage/__tests__/use-cases/upload-content-file.use-case.test.ts
apps/endatix-hub/features/storage/infrastructure/storage-service.ts
apps/endatix-hub/features/storage/use-cases/upload-content-file.use-case.ts
apps/endatix-hub/features/storage/use-cases/upload-user-files.use-case.ts
apps/endatix-hub/instrumentation.ts
apps/endatix-hub/lib/__tests__/check-node-version.test.ts
apps/endatix-hub/lib/__tests__/hosting/check-node-version.test.ts
apps/endatix-hub/lib/__tests__/hosting/runtime.test.ts
apps/endatix-hub/lib/hosting/check-node-version.ts
apps/endatix-hub/lib/hosting/runtime.ts
apps/endatix-hub/next.config.ts

This PR adds more flexibility by eliminating the hard-coded hostname in the `next.config.ts` allowing to use Next.js features in multiple environments setup. Additional changes
- adding more flexible Azure config to support both security + hostname detection. This adds two new env variables `AZURE_STORAGE_ACCOUNT_NAME` & `AZURE_STORAGE_ACCOUNT_KEY`
- fixing failing tests in the `storage-service.ts`
- adding static `getAzureStorageConfig()` const to evaluate env variables needed for Azure storage account support
- rearranging env variables for readability
- fixing edge runtime issues with `checkNodeVersion` logic in `instrumentation.ts`
- remove `AZURE_STORAGE_CONNECTION_STRING` env variable as it's redundant
- `runtime.ts` with methods to detect node.js vs edge runtime + tests
closes #357

feat: Add configurable storage hostname

---

apps/endatix-hub/app/api/public/v0/storage/upload/route.ts
apps/endatix-hub/features/public-form/application/actions/submit-form.action.ts
apps/endatix-hub/features/public-form/ui/survey-component.tsx
apps/endatix-hub/features/storage/use-cases/upload-content-file.use-case.ts
apps/endatix-hub/features/storage/use-cases/upload-user-files.use-case.ts

- Adding submissionId to storage path
- Changing folder structure for storage using agreed convention
- Refactoring file upload callback flow to async to allow for better response error handling and readability
- Improving error handling for file upload
closes #354

feat: Adding support for `submissionId` in user uploaded storage path

---

apps/endatix-hub/features/public-form/ui/survey-component.tsx
apps/endatix-hub/features/public-form/ui/survey-js-wrapper.tsx

- Add survey model event handlers disposal on unmount and key dependency changes
- Remove cookie check from form-wrapper to increase data capture scope
fixes #368

fix: Images are uploaded twice

---

src/Endatix.Infrastructure/Data/AppDbContext.cs
src/Endatix.Infrastructure/Integrations/Slack/SlackClient.cs
src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
src/Endatix.WebHost/Program.cs

Applies a global query filter for all forms with a CreatedAt date that is earlier than 2021-01-01. This filter is ignored for user accounts with @endatix.com email address.
Slack messages are skipped for all forms with CreatedAt date that is earlier than 2021-01-01.

feat: Internal test forms filtering and Slack message bypass

---

src/Endatix.Core/Specifications/Common/SpecificationHelper.cs
tests/Endatix.Core.Tests/Specifications/Common/SpecificationHelperTests.cs

When having time in API filters, the kind should be set in the DateTime objects for Postgres queries to work properly.

fix: Set DateTime kind to UTC in filters

---

src/Endatix.Core/Specifications/ActiveFormDefinitionByFormIdSpec.cs

The internal test form filter implemented with [PR 372](https://github.com/endatix/endatix/pull/372) is preventing test forms from being displayed on the public page. 

fix: Bypass EF query filter for internal test forms on the public form sharing page

---

apps/endatix-hub/lib/__tests__/hosting/next-config-helper.test.ts
apps/endatix-hub/lib/hosting/next-config-helper.ts
apps/endatix-hub/next.config.ts

- Adding setting for the header parallel route
- Adding test
- Adding setting for `@headers` parallel route
fixes #386

fix: Adding `getRewriteRuleFor` method to next-config-helpers for parallel routes

---

docs/endatix-docs/docs/getting-started/setup-nuget-package.md
src/Endatix.Api/Builders/ApiConfigurationBuilder.cs
src/Endatix.Api/Builders/ApiOptions.cs
src/Endatix.Api/Configuration/ApiConfigurationOptions.cs
src/Endatix.Api/Setup/ApiApplicationBuilderExtensions.cs
src/Endatix.Api/Setup/ApiServiceCollectionExtensions.cs
src/Endatix.Hosting/Builders/EndatixApiBuilder.cs
src/Endatix.Hosting/Builders/EndatixMessagingBuilder.cs
src/Endatix.Hosting/Builders/EndatixMiddlewareBuilder.cs
src/Endatix.Hosting/Builders/EndatixPersistenceBuilder.cs
src/Endatix.Hosting/Builders/EndatixSecurityBuilder.cs
src/Endatix.Hosting/EndatixApplicationBuilderExtensions.cs
src/Endatix.Infrastructure/Builders/InfrastructureDataBuilder.cs
src/Endatix.Infrastructure/Builders/InfrastructureIdentityBuilder.cs
src/Endatix.Infrastructure/Builders/InfrastructureIntegrationsBuilder.cs
src/Endatix.Infrastructure/Builders/InfrastructureMessagingBuilder.cs
src/Endatix.Persistence.PostgreSql/Builders/PostgreSqlPersistenceBuilder.cs

- Adds ability to control swagger and swagger path via AppSettings
- Updates SetupInfo to Debug level to reduce console verbosity on non prod environments
- Removes obsolete `UseSwaggerInProduction` config, since it is now controlled via AppSettings as well => replaced with `UseSwagger` config value
closes #410
- No config -> Swagger is enabled and used in `/api-docs`
- Development
```json
"Api": {
"UseSwagger": true,
"SwaggerPath": ""
},
```
- Production
```json
"Api": {
"UseSwagger": true,
"SwaggerPath": "/api-docs"
},
```

feat: Configure Swagger and API settings via AppSettings

---

src/Endatix.Hosting/Builders/EndatixSecurityBuilder.cs

Fixes the login issue via preventing unintended claims mapping occurred during JWT token validation
fixes #413

fix: Set MapInboundClaim to false to prevent unintended claims mapping

---

src/Endatix.Infrastructure/Setup/ServiceCollectionExtensions.cs

Adding EmailSender config registration to improve namespacing of settings.
```json
"Email": {
"SendGridSettings": {
"ApiKey": "{YOUR_SENDGRID_API_KEY_HERE}"
}
}
```
```json
"Endatix": {
"Integrations": {
"Email": {
"SendGridSettings": {
"ApiKey": "{YOUR_SENDGRID_API_KEY_HERE}"
}
}
}
```
addresses https://github.com/endatix/corp-website/issues/134

feat: Adds Endatix into the  EmailSender config namespacing

---

docs/endatix-docs/docs/building-your-solution/_category_.json
docs/endatix-docs/docs/configuration/_category_.json
docs/endatix-docs/docs/guides/_category_.json
docs/endatix-docs/docs/guides/webhooks.mdx
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-workspace.yaml
samples/Endatix.Samples.CustomEventHandlers/WebHooks/FormEventHandlers/FormCreatedHandler.cs
samples/Endatix.Samples.CustomEventHandlers/WebHooks/FormEventHandlers/FormEnabledStateChangedHandler.cs
samples/Endatix.Samples.CustomEventHandlers/WebHooks/FormEventHandlers/FormUpdatedHandler.cs
samples/Endatix.Samples.CustomEventHandlers/WebHooks/SubmissionEventHandlers/SubmissionCompletedHandler.cs
src/Endatix.Core/Events/FormCreatedEvent.cs
src/Endatix.Core/Events/FormEnabledStateChangedEvent.cs
src/Endatix.Core/Events/FormUpdatedEvent.cs
src/Endatix.Core/Features/WebHooks/WebHookOperation.cs
src/Endatix.Core/UseCases/Forms/Create/CreateFormHandler.cs
src/Endatix.Core/UseCases/Forms/PartialUpdate/PartialUpdateFormHandler.cs
src/Endatix.Core/UseCases/Forms/Update/UpdateFormHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTaskWebHookService.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookSettings.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHooksPlugin.cs
src/Endatix.WebHost/Endatix.WebHost.csproj
tests/Endatix.Core.Tests/UseCases/Forms/Create/CreateFormHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/PartialUpdate/PartialUpdateFormHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Forms/Update/UpdateFormHandlerTests.cs

Added events:
- FormCreatedEvent
- FormUpdatedEvent
- FormEnabledStateChangedEvent
Added webhook event handlers in Endatix.Samples.CustomEventHandlers project:
- FormCreatedHandler
- FormUpdatedHandler
- FormEnabledStateChangedHandler
- SubmissionCompletedHandler
#170

feat: Add form events and webhook samples

---

src/Endatix.Api/Builders/ApiConfigurationBuilder.cs
src/Endatix.Api/Endpoints/Integrations/SlackToken.cs

- Adds "hidden" Tag to the `SlackToken` endpoint
- Adds new filter based of the "hidden" tag associated with the endpoints
closes https://github.com/endatix/endatix-private/issues/208

fix: Using hidden tag to hide endpoints from the API documentation

---

src/Endatix.Api/Endpoints/Auth/Register.cs
src/Endatix.Api/Endpoints/Auth/VerifyEmail.cs
tests/Endatix.Api.Tests/Endpoints/Auth/RegisterTests.cs

Return failure details in /register and /verify-email endpoints in the cases of invalid requests
https://github.com/endatix/endatix-private/issues/139

feat: Return failure details in /register and /verify-email endpoints

---

docs/endatix-docs/docs/guides/webhooks.mdx
samples/Endatix.Samples.CustomEventHandlers/WebHooks/SubmissionEventHandlers/SubmissionCompletedHandler.cs
src/Endatix.Core/Features/WebHooks/WebHookOperation.cs
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTaskWebHookService.cs
src/Endatix.Infrastructure/Features/WebHooks/Handlers/FormCreatedHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/Handlers/FormDeletedHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/Handlers/FormEnabledStateChangedHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/Handlers/FormUpdatedHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/Handlers/SubmissionCompletedHandler.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookSettings.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHooksPlugin.cs
src/Endatix.WebHost/appsettings.Development.json
src/Endatix.WebHost/appsettings.json
tests/Endatix.Core.Tests/Features/WebHooks/WebHookMessageTests.cs
tests/Endatix.Core.Tests/Features/WebHooks/WebHookOperationTests.cs

- Use camelCase in payload field names
- FormSubmitted event becomes SubmissionCompleted
- Return submittedBy in SubmissionCompleted
closes #453

feat: Update webhooks implementation

---

docs/endatix-docs/docs/guides/webhooks.mdx
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTaskWebHookService.cs
src/Endatix.Infrastructure/Features/WebHooks/TaskInstructions.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookServer.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookSettings.cs
src/Endatix.WebHost/appsettings.Development.json
src/Endatix.WebHost/appsettings.json
tests/Endatix.Infrastructure.Tests/Features/WebHooks/BackgroundTaskWebHookServiceTests.cs
tests/Endatix.Infrastructure.Tests/Features/WebHooks/TaskInstructionsTests.cs
tests/Endatix.Infrastructure.Tests/Features/WebHooks/WebHookServerTests.cs
tests/Endatix.Infrastructure.Tests/Features/WebHooks/WebHookSettingsTests.cs

Authentication can be configured now for each webhook endpoint like
```
"WebHooks": {
"Events": {
"FormCreated": {
"IsEnabled": true,
"WebHookEndpoints": [
{
"Url": "https://api.example.com/webhooks",
"Authentication": {
"Type": "ApiKey",
"ApiKeyHeader": "X-SURVEY-API-KEY",
"ApiKey": "your-secret-api-key"
}
}
]
},
...
```
The old format
```
"WebHookUrls": [
"https://webhook.site/no-auth-endpoint"
]
```
is kept for compatibility and can be used in a mixed way with the new auth format.
There wasn't any test coverage of the webhook logic I tests were added for the files where there are changes.
Future enhancements will involve configuring per tenant and with more options.
closes #458

feat: Authenticate webhook messages

---

docs/endatix-docs/docusaurus.config.ts
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-lock.yaml

This PR also enables all v4 features
closes https://github.com/endatix/endatix/issues/461

chore: Upgrade docs to Docusaurus v3.8.1
