endatix/endatix

README.md

Enhancements of the README as a part of providing better open-source documentation.
The changes include:
- more general info about the product
- brief design and dependencies explanation
- license section
- contacts
- resources section pointing to our website
**Note:** The sections about the installation and usage have some brief or no text at all. The reason is the the main documentation about these will be on our Documentation website. When it is updated, the README will be updated having a link to there. It may also have some short summary here.
#51

docs: Enhance README

---

src/Endatix.Api/Auth/Login.cs
src/Endatix.Api/Submissions/GetById.cs

Small API documentation changes to sync with the other endpoints

docs: Small API documentation changes to sync with the other endpoints

---

.github/workflows/release.yml

ci: fixing release ci test command

---

README.md

ci: add release status badge to Readme

---

docker/README.md

There are a few URLs in docker/README.md that are wrong and need to be fixed.

docs: Fix URLs in docker/README.md

---

apps/endatix-hub/app/(auth)/login/login.action.ts
apps/endatix-hub/app/(auth)/login/page.tsx
apps/endatix-hub/app/(auth)/login/ui/login-form.tsx
apps/endatix-hub/app/(auth)/login/ui/new-account-link.tsx
apps/endatix-hub/app/error.tsx
apps/endatix-hub/components/error-boundary.tsx
apps/endatix-hub/components/layout-ui/my-account/avatar-icon.tsx
apps/endatix-hub/components/layout-ui/navigation/main-search-bar.tsx
apps/endatix-hub/components/layout-ui/navigation/nav-link.tsx
apps/endatix-hub/components/layout-ui/teasers/coming-soon-link.ts
apps/endatix-hub/lib/auth-service.ts

Fixing build errors in the hub hackathon

---

apps/endatix-hub/README.md
apps/endatix-hub/app/forms/[formId]/page.tsx
apps/endatix-hub/app/forms/[formId]/update-form-definition-json.action.ts
apps/endatix-hub/app/forms/[formId]/update-form-name.action.ts
apps/endatix-hub/app/forms/[formId]/update-form-status.action.ts
apps/endatix-hub/components/survey-creator.tsx
apps/endatix-hub/package.json
apps/endatix-hub/pnpm-lock.yaml
apps/endatix-hub/services/api.ts

Includes the page Edit Form page in Endatix Hub with hackathon level quality. The design follows the [wireframes ](https://www.figma.com/design/2bwMXMuvAOJKYXemu5HjhX/Endatix-Hub---Wireframes?node-id=0-1&node-type=canvas&t=wNT5Pb2boChRN0gM-0)
closes #119

feat: Edit Form page in Endatix Hub

---

src/Endatix.Api/Endpoints/Auth/Login.cs
src/Endatix.Api/Endpoints/Auth/Logout.LogoutResponse.cs
src/Endatix.Api/Endpoints/Auth/Logout.cs
src/Endatix.Api/Endpoints/Auth/Register.cs
src/Endatix.Api/Infrastructure/ResultExtensions.cs
src/Endatix.Api/api.http
src/Endatix.Core/Abstractions/ITokenService.cs
src/Endatix.Core/Abstractions/IUserService.cs
src/Endatix.Core/Entities/Identity/User.cs
src/Endatix.Core/UseCases/Identity/Logout/LogoutCommand.cs
src/Endatix.Core/UseCases/Identity/Logout/LogoutHandler.cs
src/Endatix.Infrastructure/Identity/AppUser.cs
src/Endatix.Infrastructure/Identity/Authentication/JwtTokenService.cs
src/Endatix.Infrastructure/Identity/IdentitySetup.cs
src/Endatix.Infrastructure/Identity/Users/AppUserRegistrationService.cs
src/Endatix.Infrastructure/Identity/Users/AppUserService.cs

- feat: Add logout functionality
- feat: Add additional ToApiEndpoint extension method for simpler flow with no mapper
- feat: Adding default claim for identifying user Id, so that ASP.NET Core Identity can operate as expected
- feat: Adding logout method in the api.http REST client examples
closes #106 
>[!NOTE]
> I haven't added unit tests for this feature, but will make sure to catch up when there's more time. I have added a slot for the token revocation in the `JwtTokenService` for the #114 feature
```c#
/// <inheritdoc />
public Task<Result> RevokeTokensAsync(User forUser, CancellationToken cancellationToken = default) {
if (forUser == null){
return Task.FromResult(Result.NotFound());
}
// Add removal of Refresh token once feature is implemented.
// Add Revoking JWT token should we …
```

feat: Add Logout functionality

---

.vscode/launch.json
samples/Endatix.Samples.WebApp/ApiClient/Common/ApiError.cs
samples/Endatix.Samples.WebApp/ApiClient/Common/ApiResult.cs
samples/Endatix.Samples.WebApp/ApiClient/Common/ErrorType.cs
samples/Endatix.Samples.WebApp/ApiClient/Common/ErrorTypeExtensions.cs
samples/Endatix.Samples.WebApp/ApiClient/EndatixClient.cs
samples/Endatix.Samples.WebApp/ApiClient/IEndatixClient.cs
samples/Endatix.Samples.WebApp/ApiClient/Model/FormModel.cs
samples/Endatix.Samples.WebApp/ApiClient/Model/Requests/FormListRequest.cs
samples/Endatix.Samples.WebApp/ApiClient/Model/Responses/FormDefinitionResponse.cs
samples/Endatix.Samples.WebApp/Pages/Edit.cshtml.cs
samples/Endatix.Samples.WebApp/Pages/Form.cshtml
samples/Endatix.Samples.WebApp/Pages/Form.cshtml.cs
samples/Endatix.Samples.WebApp/Pages/Index.cshtml
samples/Endatix.Samples.WebApp/Pages/Index.cshtml.cs
samples/Endatix.Samples.WebApp/Pages/Shared/_ErrorDetails.cshtml
samples/Endatix.Samples.WebApp/Properties/launchSettings.json
src/Endatix.Api/Endpoints/FormDefinitions/GetActive.cs
src/Endatix.Api/Endpoints/Forms/List.cs
src/Endatix.Core/Handlers/SubmissionCompletedHandler.cs
src/Endatix.Infrastructure/Email/SendGridEmailSender.cs
src/Endatix.Infrastructure/Email/SendGridSettings.cs
src/Endatix.Infrastructure/Setup/ServiceCollectionExtensions.cs
src/Endatix.WebHost/appsettings.Development.json

- Fixing server error with GetList of Forms due to `NotFound` -> `NotFound<ProblemDetails>` missing mapping
- Adding launch settings on solution level to launch sample apps alongside main Endatix.WebHost
- [⏳ Temp]  Adding anonymous access support for getting list of Forms endpoints. Will be reverted with the upcoming Authentication changes
- Improve Endatix.Api Client sample to use Railway Oriented Programming with discriminated union of Success & Error results - check `ApiResult` and `ApiError`
- Improve control flow in the Sample app for better error handling
- Adding dev friendly Error handling for Endatix.Samples.WebApp - see screenshot
Fixes #139 

feat: improve WebApp sample with list of forms support, error handling and Endatix API client goodies

---

src/Endatix.Api/Endpoints/Auth/Register.cs

Register user endpoint needs authentication to prevent uncontrolled creation of users that access all the data.
closes #174
- Send unauthenticated Register User API request to get Unauthorized status
- Send authenticated Register User API request to get a successfully created user

feat: Register user endpoint needs authentication

---

src/Endatix.Api/Endpoints/Auth/Login.cs
src/Endatix.Api/Endpoints/Auth/Logout.cs
src/Endatix.Api/Endpoints/Auth/RefreshToken.cs
src/Endatix.Api/Endpoints/Auth/Register.cs
src/Endatix.Api/Infrastructure/ResultExtensions.cs
src/Endatix.Api/Infrastructure/TypedResultsBuilder.cs
src/Endatix.Core/Abstractions/IAuthService.cs
src/Endatix.Core/Configuration/EndatixConfig.cs
src/Endatix.Core/Specifications/FormsSpec.cs
src/Endatix.Extensions.Hosting/AppBuilderExtensions.cs
src/Endatix.Extensions.Hosting/EndatixWebAppBuilderExtensions.cs
src/Endatix.Infrastructure/Identity/Authentication/AuthService.cs
src/Endatix.Infrastructure/Identity/Seed/IdentitySeed.cs
src/Endatix.Infrastructure/Setup/ApplicationBuilderExtensions.cs
tests/Endatix.Api.Tests/Endpoints/Auth/LoginTests.cs
tests/Endatix.Api.Tests/Endpoints/Auth/RefreshTokenTests.cs
tests/Endatix.Api.Tests/Endpoints/Auth/RegisterTests.cs

- Adding changes to the code for polishing the https://github.com/endatix/endatix/pull/178/files PR
- Fixing user seed logic to support running alongside DB migrations
- Fixing tests
- Adding support for TypedResultsBuilder
- Adding code documentation where applicable

fix: polish the changes of the feature/46-integrate-identity

---

src/Endatix.Api/Endpoints/Submissions/GetByToken.GetByTokenRequest.cs
src/Endatix.Api/Endpoints/Submissions/GetByToken.GetByTokenValidator.cs
src/Endatix.Api/Endpoints/Submissions/GetByToken.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.PartialUpdateSubmissionByTokenRequest.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.PartialUpdateSubmissionByTokenResponse.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.PartialUpdateSubmissionByTokenValidator.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.cs
src/Endatix.Api/Endpoints/Submissions/SubmissionMapper.cs
src/Endatix.Api/Endpoints/Submissions/SubmissionModel.cs
src/Endatix.Core/Abstractions/ISubmissionTokenService.cs
src/Endatix.Core/UseCases/Submissions/Create/CreateSubmissionHandler.cs
src/Endatix.Core/UseCases/Submissions/GetByToken/GetByTokenHandler.cs
src/Endatix.Core/UseCases/Submissions/GetByToken/GetByTokenQuery.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenCommand.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenHandler.cs
src/Endatix.Infrastructure/Features/Submissions/SubmissionTokenService.cs
tests/Endatix.Infrastructure.Tests/Features/Submissions/SubmissionTokenServiceObtainTokenTests.cs
tests/Endatix.Infrastructure.Tests/Features/Submissions/SubmissionTokenServiceResolveTokenTests.cs

Please include a summary of the changes and the related issue. Also, explain the context and the reason for the proposed changes.
List any related issues (e.g., fixes #123, addresses #456).
If applicable, add screenshots to help explain your changes.

feat: [draft] Add GetByToken and PartialUpdateByToken endpoints for submission

---

src/Endatix.Api/Endpoints/Submissions/GetById.cs
src/Endatix.Api/Endpoints/Submissions/GetByToken.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdate.cs
src/Endatix.Api/Endpoints/Submissions/PartialUpdateByToken.cs
src/Endatix.Core/UseCases/Submissions/GetById/GetByIdHandler.cs
src/Endatix.Core/UseCases/Submissions/GetById/GetByIdQuery.cs
src/Endatix.Core/UseCases/Submissions/GetByToken/GetByTokenHandler.cs
src/Endatix.Core/UseCases/Submissions/GetByToken/GetByTokenQuery.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdate/PartialUpdateSubmissionCommand.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdate/PartialUpdateSubmissionHandler.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenCommand.cs
src/Endatix.Core/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenHandler.cs
tests/Endatix.Api.Tests/Endpoints/Submissions/GetByTokenTests.cs
tests/Endatix.Api.Tests/Endpoints/Submissions/PartialUpdateByTokenTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/GetByToken/GetByTokenHandlerTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/GetByToken/GetByTokenQueryTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenCommandTests.cs
tests/Endatix.Core.Tests/UseCases/Submissions/PartialUpdateByToken/PartialUpdateSubmissionByTokenHandlerTests.cs
tests/Endatix.Infrastructure.Tests/Features/Submissions/SubmissionTokenServiceResolveTokenTests.cs

Tests for #240 and fix old wrong namespaces

feat: Add tests for submissions by token and fix namespaces

---

tests/Endatix.Core.Tests/UseCases/Submissions/Create/CreateSubmissionHandlerTests.cs

Fixing failing Metadata change

fix: Fix build

---

.github/ISSUE_TEMPLATE/feature.md

The current create new feature template has too many sections expecting details that are not applicable for every feature. This PR simplifies it. focusing on the description of what is needed, how it will be done and what are the expected results.

docs: Simplify the create new feature template

---

apps/endatix-hub/.eslintrc.json
apps/endatix-hub/app/(main)/forms/[formId]/ui/form-editor.tsx
apps/endatix-hub/app/(main)/forms/submissions/[formId]/ui/matrix-answer.tsx
apps/endatix-hub/app/(main)/forms/ui/chat-box.tsx
apps/endatix-hub/app/(main)/forms/ui/create-form-sheet.tsx

EsLinting was not working which was causing warning in the build process. This PR enables the Linting and addresses all linting errors at the time
N/A.

fix: Enabling Next.js linting and fixing all linting errors

---

.github/workflows/deploy-endatix-docs.yml
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-lock.yaml

- FIxed reported vulnerabilities from npm packages
- Changed FTP job path to pick up prod artefacts
closes #274

ci: Fix documentation site deployment issues

---

.github/workflows/build-ci.yml
apps/endatix-hub/app/(main)/forms/submissions/[formId]/ui/matrix-answer.tsx

- Addressing the build failing issue in the Matrix question
- Adding lint step in the build
N/A

ci: Addressing the build failing issue

---

tests/README.md

Add README.md in tests folder with a short guide how to use Cursor for generation of unit tests with AI and prompt.

docs: Add tests README with AI prompt

---

apps/endatix-hub/app/(main)/forms/[formId]/page.tsx
apps/endatix-hub/app/(main)/forms/[formId]/ui/form-editor.tsx

Changes to remove the unnecessary elements from Design Form screen.
**Note**
No changes were needed to name the new form as "New Form" because they were made as part of #302
closes #285

feat: Update Design Form screen according to the latest design

---

apps/endatix-hub/app/(main)/forms/page.tsx
apps/endatix-hub/app/(main)/forms/ui/form-card.tsx
apps/endatix-hub/app/(main)/forms/ui/forms-list.tsx
src/Endatix.Core/Specifications/Parameters/FilterParameters.cs
tests/Endatix.Core.Tests/Specifications/Parameters/FilterParametersTests.cs

Updates the Form Card as described in #281
**Note**
The dots menu is not added but it doesn't have any implemented actions so far.
closes #281

feat: Update Form Card according to the latest design

---

apps/endatix-hub/app/(main)/forms/[formId]/loading.tsx
apps/endatix-hub/app/(main)/forms/[formId]/page.tsx
apps/endatix-hub/app/(main)/forms/[formId]/submissions/[submissionId]/page.tsx
apps/endatix-hub/app/(main)/forms/[formId]/submissions/page.tsx
apps/endatix-hub/app/(main)/forms/page.tsx
apps/endatix-hub/features/submissions/ui/details/submission-actions-dropdown.tsx
apps/endatix-hub/features/submissions/ui/details/submission-header.tsx
apps/endatix-hub/lib/utils.ts

- Adding loading state for **forms page** via React Suspense and Next.js Streaming
- Adding loading experience for **submissions page** via React Suspense and Next.js Streaming
- Adding loading experience for **submission details page** via React Suspense and Next.js Streaming
- Adding loading experience for **editor page** via React Suspense and Next.js Streaming
- Adding Util for sleep thread in 
closes #317

feat: Adding Loading experience

---

apps/endatix-hub/next.config.ts

Increases server action payload limit to 30Mb.
-

feat: Increase server action limit to 30Mb

---

apps/endatix-hub/.env.example
apps/endatix-hub/README.md
src/Endatix.Api/Setup/MiddlewareExtensions.cs

- Enables Swagger on / instead of redirect
- Adding Readme improvements + `.env.example`

feat: Enable Swagger

---

apps/endatix-hub/.env.example
apps/endatix-hub/app/api/public/v0/storage/upload/route.ts
apps/endatix-hub/env.d.ts
apps/endatix-hub/features/public-form/ui/survey-component.tsx
apps/endatix-hub/next.config.ts
apps/endatix-hub/package.json
apps/endatix-hub/pnpm-lock.yaml

- first version of BLOB images with nondeterministic folder name resolution per submission
- adding image resize as well
closes #328

feat: Adding BLOB Storage for user generated images

---

apps/endatix-hub/features/public-form/application/actions/submit-form.action.ts
apps/endatix-hub/features/public-form/ui/survey-component.tsx

Control the Thank you page flow and message
>[!NOTE]
>The fix is not verified and exact root cause is not pinpointed 📌 . Still it's a step in the right direction
fixes #333

fix: Adding thank you page state control

---

src/Endatix.Api/Endpoints/Auth/Login.LoginRequest.cs
src/Endatix.Api/Endpoints/Auth/Register.RegisterRequest.cs
src/Endatix.Core/Infrastructure/Attributes/SensitiveAttribute.cs
src/Endatix.Core/Infrastructure/Logging/LoggingPipelineBehavior.cs
src/Endatix.Core/UseCases/Identity/Login/LoginCommand.cs
src/Endatix.Core/UseCases/Identity/Register/RegisterCommand.cs
tests/Endatix.Core.Tests/Infrastructure/Logging/LoggingPipelineBehaviorTests.cs

A new attribute `Sensitive` is introduced and used for passwords in Login and Register user requests and commands. Changes are made in the logging middleware to mask sensitive data on logging with 10 asterisk long string.

feat: Mask sensitive data

---

apps/endatix-hub/next.config.ts

Please include a summary of the changes and the related issue. Also, explain the context and the reason for the proposed changes.
List any related issues (e.g., fixes #123, addresses #456).
- [ x ] New feature (non-breaking change which adds functionality)

feat: Environment variable for image host

---

.vscode/extensions.json
.vscode/settings.json
apps/endatix-hub/app/(main)/forms/[formId]/submissions/[submissionId]/page.tsx
apps/endatix-hub/features/storage/infrastructure/storage-service.ts
apps/endatix-hub/features/submissions/pdf/pdf-answer-viewer.tsx
apps/endatix-hub/features/submissions/ui/answers/answer-viewer.tsx
apps/endatix-hub/features/submissions/ui/answers/file-answer.tsx
apps/endatix-hub/lib/__tests__/utils/type-parsers.test.ts
apps/endatix-hub/lib/utils/type-parsers.ts
apps/endatix-hub/package.json
apps/endatix-hub/pnpm-lock.yaml
apps/endatix-hub/tsconfig.json

Please include a summary of the changes and the related issue. Also, explain the context and the reason for the proposed changes.
- fixes https://github.com/endatix/endatix-private/issues/50
- fixes https://github.com/endatix/endatix-private/issues/52

fix: fix rendering for File Upload Comment

---

apps/endatix-hub/app/(main)/forms/[formId]/submissions/[submissionId]/page.tsx
apps/endatix-hub/app/api/public/v0/forms/[formId]/submissions/[submissionId]/export-pdf/route.tsx
apps/endatix-hub/features/pdf-export/components/pdf-embed-view.tsx
apps/endatix-hub/features/submissions/pdf/pdf-file-answer.tsx
apps/endatix-hub/features/submissions/ui/answers/file-answer.tsx

- Fixing issues with empty file parsing
- Fixing issues with large Pdf files
- DRY on pdf generation
fixes https://github.com/endatix/endatix-private/issues/90

fix: Submission details error

---

apps/endatix-hub/features/submissions/ui/edit/edit-survey-wrapper.tsx

fixes https://github.com/endatix/endatix-private/issues/92

fix: Switched to single page mode to fix issues with the edit submission page

---

apps/endatix-hub/components/ui/table.tsx
apps/endatix-hub/features/submissions/ui/table/row-actions.tsx

- Adding hover effect to table rows and actions menu
- Additional accessibility features
closes https://github.com/endatix/endatix-private/issues/109

feat: Adding hover effect to table rows and actions menu

---

apps/endatix-hub/app/(main)/forms/[formId]/ui/form-editor.tsx

- [Adding fix via force expanding the panel when added](https://github.com/endatix/endatix/commit/f197b89a0591714b90a10d2a464c37cc99a55d06)
fixes #388

fix: Adding fix via force expanding the panel when added

---

docs/endatix-docs/docs/getting-started/architecture.md

Update the architecture page with info on new projects
closes https://github.com/endatix/business/issues/138
If applicable, add screenshots to help explain your changes.

chore: Update architecture with new projects part of the solution

---

docs/endatix-docs/docusaurus.config.ts
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-lock.yaml

chore: Adding Google Tag Manager to docs

---

docs/endatix-docs/docs/building-your-solution/authentication.mdx
docs/endatix-docs/docs/building-your-solution/index.mdx
docs/endatix-docs/docs/configuration/settings/index.mdx
docs/endatix-docs/docs/getting-started/setup-nuget-package.mdx
docs/endatix-docs/docs/getting-started/setup-repository.md
docs/endatix-docs/docs/getting-started/what-is-endatix.md
docs/endatix-docs/docusaurus.config.ts
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-lock.yaml

docs: fix broken links in doc site

---

docs/endatix-docs/docusaurus.config.ts
docs/endatix-docs/package.json
docs/endatix-docs/pnpm-lock.yaml

- Fix GTM Container Id
- Adds correct plugin

fix: GTM container ID

---

.github/workflows/deploy-endatix-docs.yml
src/Endatix.Core/Specifications/SubmissionsByFormIdSpec.cs

- Fixing the default submissions sorting expression to address issue captured during the e2e tests execution
- Updating the pnpm version to 10.10.0 across the project
related to https://github.com/endatix/endatix-private/issues/170

chore: Fixing the default submissions sorting expression + pnpm version upgrade

---

src/Endatix.Core/Features/WebHooks/WebHookMessage.cs
src/Endatix.Infrastructure/Features/WebHooks/BackgroundTaskWebHookService.cs
src/Endatix.Infrastructure/Features/WebHooks/WebHookServer.cs
tests/Endatix.Core.Tests/Features/WebHooks/WebHookMessageTests.cs

feat: Change the remaining webhook field names to camelCase

---

src/Endatix.Api/Infrastructure/ResultExtensions.cs
tests/Endatix.Api.Tests/Infrastructure/ResultExtensionsTests.cs

As part of the work on https://github.com/endatix/endatix-private/issues/234, we discovered an issue with ProblemDetails having wrong mapping and logic for the details field
- Added basic logic for Problem Details response "Details" field
- Default unexpected error message changed from "Something went wrong" to "An unexpected error occurred."
- Tests to verify logic
- related to https://github.com/endatix/endatix-private/issues/234
N/A

fix: Problem error details
